### ISSUE TITLE
I'm unable to join the slack workspace using the link provided in the main page

### ISSUE THREAD

**Issue by Rustotronics** [atsam4-rs/atsam4-pac#26]
Hi, I've ATSAM4L8 Xplained Pro board and I wanted to get started on embedded rust with this board. I've recently started working on embedded rust and I was wondering if I could get some help getting started. The slack workspace seemed like it would be a good start but I'm unable to join. Can you help me out here? Thanks!

**Comment by haata** [comment]
Send your email to haata@kiibohd.com and I'll get you added.

**Comment by haata** [comment]
Invited
